#!/usr/bin/env bash
set -e

KEY="$HOME/.ssh/id_ed25519"
REAL_SSH_KEYGEN=$(which ssh-keygen)

if ! ssh-add -l 2>/dev/null | grep -q "$(ssh-keygen -lf "$KEY" | awk '{print $2}')"; then
  unset SSH_ASKPASS
  SSH_ASKPASS_REQUIRE=never ssh-add "$KEY" < /dev/tty
fi

exec "$REAL_SSH_KEYGEN" "$@"
