#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d 0 1 2 3 4 5 6 7 8 9

bspc config border_width          0
bspc config window_gap            12
bspc config ignore_ewmh_focus     true
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_follows_pointer true
bspc config pointer_modifier      control

# Rules
bspc rule -a pentablet desktop='I' follow=off focus=off
bspc rule -a krita desktop='I' follow=off focus=off
# bspc rule -a Xournalpp desktop='6' follow=off focus=off
bspc rule -a zoom follow=off focus=off state=floating
bspc rule -a 'zoom ' follow=off focus=off state=floating
bspc rule -a 'tidal-hifi' follow=off focus=on state=floating

# Set monitor layout
xrandr --output HDMI-0 --primary --mode 3840x2160 --rate 144 --pos 0x0 &

# Init compositor
picom &

# Set wallpapers
nitrogen --restore &

# Polybar
left_padding=$(bspc config -m HDMI-0 left_padding)
total_padding=$(($left_padding+$(bspc config -m HDMI-0 right_padding)))
window_gap=$(bspc config window_gap)
WIDTH=$((3840-$total_padding-$window_gap-$window_gap)) OFFSET=$(($window_gap+$left_padding)) ~/.config/polybar/launch.sh &

#
# Launch things
#
# pgrep -x /usr/lib/pentablet/pentablet > /dev/null || bash /usr/lib/pentablet/pentablet.sh &
