#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-1 -d 1
bspc monitor DP-2 -d 2 3 4 5
bspc monitor HDMI-1 -d 6

# source pywal colors
. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color0"
bspc config active_border_color "$color6"
bspc config focused_border_color "$color7"

bspc config border_width          1
bspc config window_gap            12
bspc config ignore_ewmh_focus     true
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_follows_pointer true
bspc config pointer_modifier      control

# Rules
bspc rule -a Slack:slack node=@^1:^1:/1
bspc rule -a tidal-hifi:tidal-hifi node=@^1:^1:/2/1
bspc rule -a Gnome-calendar:gnome-calendar node=@^1:^1:/2/2
bspc rule -a Geary desktop='^3' follow=off focus=off
bspc rule -a krita desktop='6' follow=off focus=off
bspc rule -a Xournalpp desktop='6' follow=off focus=off

# Init compositor
picom &
# Set wallpapers
nitrogen --restore &
wal -R -n &
# Set monitor layout
xrandr --output DP-2 --primary --pos 0x1440 --output DP-1 --pos 420x0 --output HDMI-1 --pos 760x2880 &

#
bash ~/.config/polybar/launch.sh &

#
# Launch apps
#
if [[ ! -f ~/.bspwm_init ]]; then
	#bspc wm -l ~/.config/bspwm/launch_state.json

	slack &
	pgrep -x tidal-hifi > /dev/null || tidal-hifi &
	pgrep -x gnome-calendar > /dev/null || gnome-calendar &
	pgrep -x geary > /dev/null || geary &

	touch ~/.bspwm_init
fi

