#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1
bspc monitor DP-2 -d 2 3 4 5
bspc monitor HDMI-0 -d 6

bspc config border_width          0
bspc config window_gap            12
bspc config ignore_ewmh_focus     true
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       false
bspc config focus_follows_pointer true
bspc config pointer_modifier      control

# Rules
bspc rule -a pentablet desktop='6' follow=off focus=off
bspc rule -a krita desktop='6' follow=off focus=off
bspc rule -a Xournalpp desktop='6' follow=off focus=off
bspc rule -a zoom follow=off focus=off state=floating
bspc rule -a 'zoom ' follow=off focus=off state=floating
bspc rule -a discord desktop='5' follow=off focur=off

# Init compositor
picom &

# Set wallpapers
nitrogen --restore &

# Set monitor layout
xrandr --output DP-2 --primary --pos 0x1440 --output DP-0 --pos 420x0 --output HDMI-0 --pos 760x2880 &

# Polybar
left_padding=$(bspc config -m DP-2 left_padding)
total_padding=$(($left_padding+$(bspc config -m DP-2 right_padding)))
window_gap=$(bspc config window_gap)
WIDTH=$((3440-$total_padding-$window_gap-$window_gap)) OFFSET=$(($window_gap+$left_padding)) ~/.config/polybar/launch.sh &

#
# Launch things
#
pgrep -x /usr/lib/pentablet/pentablet > /dev/null || bash /usr/lib/pentablet/pentablet.sh &
