vim.keymap.set('n', '<leader>g<space>', ":G<space>")
vim.keymap.set('n', '<leader>gb', ":G blame<cr>")
vim.keymap.set('n', '<leader>gl', ":G log<cr>")
vim.keymap.set('n', '<leader>gph', ":G push<cr>")
vim.keymap.set('n', '<leader>gpl', ":G pull<cr>")
vim.keymap.set('n', '<leader>gpr', ":G pull --rebase origin main<cr>")
